name: button-interrupt test
version: 1
author: Sergio Gasquez Arcos

steps:
  - wait-serial: "Hello world!"
  # Press once
  - set-control:
      part-id: btn1
      control: pressed
      value: 1
  - delay: 100ms
  - set-control:
      part-id: btn1
      control: pressed
      value: 0
  - wait-serial: "Button pressed!"
